### ISSUE TITLE
[REQ] Set the license on GH

### ISSUE THREAD

**Issue by MarcoRavich** [ahmetcanaydemir/sekte#1]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project](https://github.com/forart/HyMPS) (under the [Tools section](https://github.com/forart/HyMPS/blob/main/A_Tools.md)), can you please set licensing terms for this git ?

Our "problem" is that does not generates a correct badge: 

![](https://flat.badgen.net/github/license/ahmetcanaydemir/sekte/?label=LICENSE)
(generate string: https://flat.badgen.net/github/license/ahmetcanaydemir/sekte/?label=LICENSE)

Thanks in advance.

**Comment by ahmetcanaydemir** [comment]
added

**Comment by MarcoRavich** [comment]
Worked, thank you so mutch !

Let us know if you have suggestions about the collection organization/presentation: for now, we have a new layout (the [Audio Tools section](https://github.com/forart/HyMPS/blob/main/A_Tools.md) one, where [Sekte is listed](https://github.com/forart/HyMPS/blob/main/A_Tools.md#noisereducing-) !) that we wanna apply to all other sections...

...but we need some feedbacks: https://github.com/forart/HyMPS/discussions/11

Thanks again for the volunteer work you do.
